### ISSUE TITLE
Rules are not loaded

### ISSUE THREAD

**Issue by thelittlefireman** [patros/docker-nginx-waf#28]
Seems to be an error.

Modsecurity is correctly loaded by no rules are workings.

that's seems to be related to `Include /usr/local/owasp-modsecurity-crs/rules/*.conf`

Like in this issue https://github.com/SpiderLabs/ModSecurity-nginx/issues/39

i don't know why it was working before and now it's broken :(

**Comment by coderpatros** [comment]
That's pretty strange @thelittlefireman, the tests should catch something like that.

Can you share any more details on how you are configuring/running it? Or, more ideally, a local reproduction of the issue?

**Comment by thelittlefireman** [comment]
I figured it out. It was my mistake on a  config file. Sorry for that useless issue

**Comment by coderpatros** [comment]
Thanks @thelittlefireman that's a relief. I had to double check prod when I saw this issue :)
